### ISSUE TITLE
Does not build on current distros

### ISSUE THREAD

**Issue by g3force** [robotics-erlangen/autoref#1]
I get an error when build on Fedora 26 and Ubuntu 17.10:
```
[ 58%] Building CXX object src/framework/src/amun/strategy/CMakeFiles/strategy.dir/lua.cpp.o
/home/n.ommer/git/ssl-autorefs/erforce/src/framework/src/amun/strategy/lua.cpp: In function ‘int luaLoadInitScript(lua_State*)’:
/home/n.ommer/git/ssl-autorefs/erforce/src/framework/src/amun/strategy/lua.cpp:88:25: error: ‘LUA_GLOBALSINDEX’ was not declared in this scope
     lua_getfield(state, LUA_GLOBALSINDEX, "require");
                         ^~~~~~~~~~~~~~~~
/home/n.ommer/git/ssl-autorefs/erforce/src/framework/src/amun/strategy/lua.cpp:88:25: note: suggested alternative: ‘LUA_HOOKLINE’
     lua_getfield(state, LUA_GLOBALSINDEX, "require");
                         ^~~~~~~~~~~~~~~~
                         LUA_HOOKLINE
/home/n.ommer/git/ssl-autorefs/erforce/src/framework/src/amun/strategy/lua.cpp: In function ‘void luaDebugHook(lua_State*, lua_Debug*)’:
/home/n.ommer/git/ssl-autorefs/erforce/src/framework/src/amun/strategy/lua.cpp:270:10: error: ‘LUA_HOOKTAILRET’ was not declared in this scope
     case LUA_HOOKTAILRET:
          ^~~~~~~~~~~~~~~
/home/n.ommer/git/ssl-autorefs/erforce/src/framework/src/amun/strategy/lua.cpp:270:10: note: suggested alternative: ‘LUA_HOOKTAILCALL’
     case LUA_HOOKTAILRET:
          ^~~~~~~~~~~~~~~
          LUA_HOOKTAILCALL
/home/n.ommer/git/ssl-autorefs/erforce/src/framework/src/amun/strategy/lua.cpp: In member function ‘void Lua::loadLibs()’:
/home/n.ommer/git/ssl-autorefs/erforce/src/framework/src/amun/strategy/lua.cpp:538:13: error: ‘LUA_FFILIBNAME’ was not declared in this scope
     loadLib(LUA_FFILIBNAME,     luaopen_ffi);
             ^~~~~~~~~~~~~~
/home/n.ommer/git/ssl-autorefs/erforce/src/framework/src/amun/strategy/lua.cpp:538:13: note: suggested alternative: ‘LUA_DBLIBNAME’
     loadLib(LUA_FFILIBNAME,     luaopen_ffi);
             ^~~~~~~~~~~~~~
             LUA_DBLIBNAME
/home/n.ommer/git/ssl-autorefs/erforce/src/framework/src/amun/strategy/lua.cpp:538:33: error: ‘luaopen_ffi’ was not declared in this scope
     loadLib(LUA_FFILIBNAME,     luaopen_ffi);
                                 ^~~~~~~~~~~
/home/n.ommer/git/ssl-autorefs/erforce/src/framework/src/amun/strategy/lua.cpp:538:33: note: suggested alternative: ‘luaopen_utf8’
     loadLib(LUA_FFILIBNAME,     luaopen_ffi);
                                 ^~~~~~~~~~~
                                 luaopen_utf8
/home/n.ommer/git/ssl-autorefs/erforce/src/framework/src/amun/strategy/lua.cpp: In member function ‘void Lua::loadDebugLibs()’:
/home/n.ommer/git/ssl-autorefs/erforce/src/framework/src/amun/strategy/lua.cpp:561:33: error: ‘luaopen_bit’ was not declared in this scope
     loadLib(LUA_BITLIBNAME,     luaopen_bit);
                                 ^~~~~~~~~~~
/home/n.ommer/git/ssl-autorefs/erforce/src/framework/src/amun/strategy/lua.cpp:561:33: note: suggested alternative: ‘luaopen_bit32’
     loadLib(LUA_BITLIBNAME,     luaopen_bit);
                                 ^~~~~~~~~~~
                                 luaopen_bit32
/home/n.ommer/git/ssl-autorefs/erforce/src/framework/src/amun/strategy/lua.cpp:562:13: error: ‘LUA_JITLIBNAME’ was not declared in this scope
     loadLib(LUA_JITLIBNAME,     luaopen_jit);
             ^~~~~~~~~~~~~~
/home/n.ommer/git/ssl-autorefs/erforce/src/framework/src/amun/strategy/lua.cpp:562:13: note: suggested alternative: ‘LUA_BITLIBNAME’
     loadLib(LUA_JITLIBNAME,     luaopen_jit);
             ^~~~~~~~~~~~~~
             LUA_BITLIBNAME
/home/n.ommer/git/ssl-autorefs/erforce/src/framework/src/amun/strategy/lua.cpp:562:33: error: ‘luaopen_jit’ was not declared in this scope
     loadLib(LUA_JITLIBNAME,     luaopen_jit);
                                 ^~~~~~~~~~~
/home/n.ommer/git/ssl-autorefs/erforce/src/framework/src/amun/strategy/lua.cpp:562:33: note: suggested alternative: ‘luaopen_io’
     loadLib(LUA_JITLIBNAME,     luaopen_jit);
                                 ^~~~~~~~~~~
                                 luaopen_io
make[2]: *** [src/framework/src/amun/strategy/CMakeFiles/strategy.dir/build.make:111: src/framework/src/amun/strategy/CMakeFiles/strategy.dir/lua.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:595: src/framework/src/amun/strategy/CMakeFiles/strategy.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```
I started setting up a new repo with all three autorefs and install+build scripts for easier use. You can also find a Docker file for ubuntu 16.04 und 17.10 to reproduce the error. In 16.04, the build succeeds, in 17.10 it fails.

**Comment by MichaelEischer** [comment]
I'm unable to reproduce the build failure on Ubuntu 17.10 with your Dockerfile from https://github.com/g3force/ssl-autorefs . The autoref builds fine for me. I'm rather surprised to see that the container behaves differently for me.

Regarding the installDeps.sh file: The lua-devel package for Fedora seems unnecessary for me and might be the cause of the problems: It installs lua5.3 (at least thats what I assume) which is incompatible with luajit. For some reason the lua5.3 header files are installed directly into /usr/include (no versioned subfolder!). From there the `lua.h` (or a similar file) could be picked up by the luajit header files.

I had hoped to have fixed the include paths in https://github.com/robotics-erlangen/framework/commit/2743f98ddebdf09ae53fba20d988d54b424791a0 but it seems like there are some remaining problems...

**Comment by g3force** [comment]
I retried the build with Docker and 17.10 and can not reproduce it now either... The image had changed 4 days ago on Docker Hub, which is after I had initially tested it. Might be a reason, although I rather believe I mixed something up...
In any case, the log from above is from my Fedora system. I've removed the lua-devel package and got:
```
In file included from /home/n.ommer/git/ssl-autorefs/erforce/src/framework/src/amun/strategy/lua.cpp:21:0:
/home/n.ommer/git/ssl-autorefs/erforce/src/framework/src/amun/strategy/lua.h:24:10: fatal error: lua.hpp: No such file or directory
 #include <lua.hpp>
          ^~~~~~~~~
compilation terminated.
make[2]: *** [src/framework/src/amun/strategy/CMakeFiles/strategy.dir/build.make:111: src/framework/src/amun/strategy/CMakeFiles/strategy.dir/lua.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:595: src/framework/src/amun/strategy/CMakeFiles/strategy.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```
Turned out cmake is unable to find luajit:
`-- Could NOT find LUAJIT (missing: LUAJIT_INCLUDE_DIR)`
When I point to it manually, the autoref builds fine for me too:
`cmake .. -DLUAJIT_INCLUDE_DIR=/usr/include/luajit-2.1/`

**Comment by MichaelEischer** [comment]
The luajit version explains the problem: FindLuaJIT.cmake searches for luajit-2.0 not 2.1. My last tests with luajit 2.1 were rather unpleasant, as the performance regressed a lot (a least for our codebase) and the new profiler hangs the strategy thread after a few seconds.

I'll publish some patches we use internally, which avoid the system luajit and build luajit-2.0.5 instead. Not sure whether I get to it tomorrow. The only downside seems to be that building in folders whose path contains spaces is no longer possible.

**Comment by MichaelEischer** [comment]
Btw: Build using paths with spaces should continue to work.

**Comment by g3force** [comment]
thx, builds fine now
